### PR TITLE
Travis deploy and Riot build script

### LINKED ISSUE #107: Setup gh-pages
Just means having a bot (Travis can do this, I believe) that pushes the contents of `site/` from master to the gh-pages branch. `site/` is now entirely static.

Assigning @towerofnix since they're the repo admin.

### PR DESCRIPTION
**Pull request by towerofnix**
Fixes #107. Building on #77. This *does not* include source maps because I couldn't figure out how to get them to work, and I'm quite certain we aren't going to be using Riot in the future anyways.

I don't know how to test Travis. Maybe pushing .travis.yml will do something. :woman_shrugging:

### CODE REVIEW

**Comment by heyitsmeuralex** [comment]
>>>I'm quite certain we aren't going to be using Riot in the future anyways.

oof

**Comment by towerofnix** [comment]
\>oof
\>oof
\>https://github.com/heyitsmeuralex/oof

**Comment by towerofnix** [comment]
@heyitsmeuralex Build passed so I *think* this can be merged now?

**Comment by towerofnix** [comment]
> The travis build script needs to unpack site/ to /.

@heyitsmeuralex I'm not sure how to do that.. :taco:

I followed the [documentation](https://docs.travis-ci.com/user/deployment/pages/) and they didn't mention anything like that - I thought that specifying `site/` as `local_dir` would automatically push its contents to the `(branch: gh-pages) /index.html`, etc.

**Comment by heyitsmeuralex** [comment]
Oh, it may do that. Let's see.

**Comment by towerofnix** [comment]
Build worked, but no deploy occurred. :thinking:

**Pull request merged**
